# yamllint disable rule:line-length
---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

users:
  ## change this to the username you want to use
  simon:  
    disabled: false
    ## change this to the display name you want to use
    displayname: "Simon"  
    ## Generate the argon 2 password hash using the following command
    ## sudo docker run --rm authelia/authelia:latest authelia crypto hash generate argon2 --password 'yourpassword'
    ## (currently the password is 'password')
    password: "$argon2id$v=19$m=65536,t=3,p=4$sf/Xi2aRFTBU8ddVAopJ6A$YOSV34RTQvKVGbziwDw6CACtOSfqVxTzqmyFVXnqXvY"  
    email: hello@simoncaignart.com
    groups:
      - admins
      - dev
...
# yamllint enable rule:line-length
